baseURL = "https://markallison.co.uk/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Mark Allison"
enableEmoji = "true"
enableRobotsTXT = true
theme = "LoveIt"
enableGitInfo = true


[params]
  version = "0.2.X"
  defaultTheme = "auto"
  gitRepo = ""
  dateFormat = "Mon, 2 January 2006"

# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    
    [params.header.title]
      name = "Mark Allison"
      pre = "<i class='fas fa-home fa-fw'>&nbsp;</i>"
      post = ""
      typeit = false

  # Footer config
  [params.footer]
    enable = false
    hugo = true
    copyright = true
    author = true
    since = 2021

  [params.section]
    paginate = 20
    # date format (month and day)
    dateFormat = "2-Jan"
    rss = 10

  [params.list]
    paginate = 20
    # date format (month and day)
    dateFormat = "2-Jan"
    rss = 10    

  [params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = false
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false   
    [params.page.toc]
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    [params.page.share]
          enable = true
          Twitter = true
          LinkedIn = true
          Whatsapp = true
    [params.page.comment]
        enable = false
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = "markallisongit/blog"
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "/images/markallison.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Welcome"
      # subtitle shown in home page
      subtitle = "A blog about Cloud Computing, Data and DevOps"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
  [params.social]
    GitHub = "markallisongit"
    Linkedin = "markallison"
    Email = "home@markallison.co.uk"
    Twitter = "dataguzzle"
    RSS = true # LoveIt NEW | 0.2.0
  # TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 60
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = 60    
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-PLWCT0MJK3"    
   
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='fas fa-blog fa-fw'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Show all blog posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "<i class='fas fa-tags fa-fw'></i>"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = "<i class='far fa-folder'></i>"
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = "<i class='far fa-address-card fa-fw'></i>"
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4
[author]
  name = "Mark Allison"
  email = "home@markallison.co.uk"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "blog/:filename"    

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5  