baseURL = "https://markallison.co.uk/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Mark Allison"
enableEmoji = "true"
enableRobotsTXT = true
theme = "LoveIt"

[params]
  version = "0.2.X"
  defaultTheme = "dark"
  gitRepo = "https://github.com/markallisongit/blog"
  dateFormat = "Mon, 2 January 2006"

# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    
    [params.header.title]
      name = "Mark Allison"
      pre = ""
      post = ""
      typeit = false

  # Footer config
  [params.footer]
    enable = false
    hugo = true
    copyright = true
    author = true
    since = 2021

  [params.section]
    paginate = 20
    # date format (month and day)
    dateFormat = "2-Jan"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "2-Jan"
    rss = 10    

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "markallison.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Welcome"
      # subtitle shown in home page
      subtitle = "A blog about Cloud Computing, Data and DevOps"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
  [params.social]
    GitHub = "markallisongit"
    Linkedin = "markallison"
    Email = "home@markallison.co.uk"
    Twitter = "dataguzzle"
    RSS = true # LoveIt NEW | 0.2.0
  [params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = true
    # whether to enable lightgallery
    lightgallery = false
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false   

  [params.page.share]
        enable = true
        Twitter = true
        LinkedIn = true
        Whatsapp = true
  [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        # LoveIt NEW | 0.1.1
        enable = true
        # Disqus shortname to use Disqus in posts
        shortname = "markallison"        
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Show all blog posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4
[author]
  name = "Mark Allison"
  email = "home@markallison.co.uk"
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "G-PLWCT0MJK3"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4