baseURL: 'https://markallison.co.uk/'
theme: ["PaperMod"]
title: Mark Allison
pagination.pagerSize: 10

permalinks:
  posts: /blog/:filename/

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  minifyOutput: true
  disableXML: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mark Allison
  description: "A blog about Cloud Computing, Data and DevOps"
  keywords: [Azure, SQL Server, Data, DevOps, Cloud Computing]
  author: ["Mark Allison"]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: 'Mon, 2 January 2006'
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  customCSS: ["css/custom.css"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋"
    Content: 
      Welcome to my tech blog, where I write about Cloud Computing, Data and DevOps.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/markallison/"
    - name: email
      url: "blog@markallison.co.uk"
    - name: github
      url: "https://github.com/markallisongit"      

  analytics:
    google:
      SiteVerificationTag: "G-PLWCT0MJK3"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    enabled: false

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 100
    threshold: 0.3
    minMatchCharLength: 2
    limit: 10
    keys: ["title", "summary", "content"]


menu:
  main:
    - identifier: posts
      pre: <i class='fas fa-blog fa-fw'></i>
      post: ''
      name: Posts
      url: /posts/
      title: Show all blog posts
      weight: 1
    - identifier: tags
      pre: <i class='fas fa-tags fa-fw'></i>
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2
    - identifier: about
      pre: <i class='far fa-address-card fa-fw'></i>
      post: ''
      name: About
      url: /about/
      title: ''
      weight: 3  
    - identifier: search
      pre: <i class='fas fa-search fa-fw'></i>
      post: ''
      name: Search
      url: /search/
      title: 'Search the site'
      weight: 4    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search