[build]
publish = "public"
command = "hugo --gc"

[build.environment]
HUGO_VERSION = "0.143.1"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --gc --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_ENV = "development"