[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.92"
HUGO_ENV = "production"
command = "hugo --gc"

[context.branch-deploy.environment]
HUGO_VERSION = "0.93"
command = "hugo --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.2"
command = "hugo --buildFuture"