[build]
publish = "public"
command = "hugo --gc"

[build.environment]
HUGO_VERSION = "0.125.5"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --gc --buildFuture"

[context.branch-deploy.environment]
HUGO_ENV = "development"